apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-controller
  labels:
    app: k8-ingress-lb
spec:
  replicas: 1
  selector:
    app: k8-ingress-lb
  template:
    metadata:
      labels:
        app: k8-ingress-lb
        name: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: nginx-ingress-lb
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /healthz
#            port: 10254
#            scheme: HTTP
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 10254
#            scheme: HTTP
#          initialDelaySeconds: 10
#          timeoutSeconds: 1
        env:
          - name: POD_NAME
            value: "nginx-ingress-lb"
          - name: POD_NAMESPACE
            value: "che"
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=default/echoheaders-default